server.port=8082
server.tomcat.max-threads=800
server.tomcat.min-spare-threads=10
server.tomcat.accept-count=2000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=3000MB
spring.servlet.multipart.max-request-size=3000MB
